language: python
os:
 - osx
 - linux

sudo: false

#cache:
#  directories:
#    - $HOME/miniconda
#  timeout: 480
#before_cache:
#  # Remove since we're caching the extracted directories
#  - conda clean -ilps -v
#  - rm -rvf "${MINICONDA_DIR}/conda-bld/"

env:
  global:
    - MINICONDA_DIR="$HOME/miniconda"
    - PYTHONHASHSEED=0
    - OMP_NUM_THREADS=2
    - PYEMMA_NJOBS=1
    - MACOSX_DEPLOYMENT_TARGET=10.9
  matrix:
    - CONDA_PY=3.5
    - CONDA_PY=3.6


  before_install:
    - source devtools/ci/travis/install_miniconda.sh
  script:
    - pytest
