language: python
python:
  - "3.6.1"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python setup.py test
after_success:
  - bash <(curl -s https://codecov.io/bash)
